[34m[1mwandb[0m: [33mWARNING[0m WandbCallback is deprecated and will be removed in a future release. Please use the WandbMetricsLogger, WandbModelCheckpoint, and WandbEvalCallback callbacks instead. See https://docs.wandb.ai/guides/integrations/keras for more information.
[34m[1mwandb[0m: [33mWARNING[0m The save_model argument by default saves the model in the HDF5 format that cannot save custom objects like subclassed models and custom layers. This behavior will be deprecated in a future release in favor of the SavedModel format. Meanwhile, the HDF5 model is saved as W&B files and the SavedModel as W&B Artifacts.
Epoch 1/5
Traceback (most recent call last):
  File "C:\Dropbox\Jeff Lai\NTUT\subjects\113-1\äººå·¥æ™ºæ…§\ä½œæ¥­äºŒ\NN_mnist.py", line 120, in <module>
    cat_model.train_and_evaluate()
  File "C:\Dropbox\Jeff Lai\NTUT\subjects\113-1\äººå·¥æ™ºæ…§\ä½œæ¥­äºŒ\NN_mnist.py", line 47, in train_and_evaluate
    self.network.fit(
  File "C:\Dropbox\Jeff Lai\NTUT\subjects\113-1\äººå·¥æ™ºæ…§\ä½œæ¥­äºŒ\env\lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Dropbox\Jeff Lai\NTUT\subjects\113-1\äººå·¥æ™ºæ…§\ä½œæ¥­äºŒ\env\lib\site-packages\wandb\integration\keras\keras.py", line 666, in on_train_batch_end
    wandb.run.summary["graph"] = wandb.Graph.from_keras(self.model)
  File "C:\Dropbox\Jeff Lai\NTUT\subjects\113-1\äººå·¥æ™ºæ…§\ä½œæ¥­äºŒ\env\lib\site-packages\wandb\sdk\data_types\graph.py", line 357, in from_keras
    for in_layer in _nest(in_node.inbound_layers):
AttributeError: 'Node' object has no attribute 'inbound_layers'
